Fix error when compiling ruy_test_overflow_dst_zero_point with GCC
This fixes the following compilation error:

```
In file included from /usr/include/c++/10/vector:67,
                 from /home/keichi/Projects/ruy/ruy/test_overflow_dst_zero_point.cc:32:
/usr/include/c++/10/bits/stl_vector.h: In instantiation of ‘class std::vector<const signed char>’:
/home/keichi/Projects/ruy/ruy/test_overflow_dst_zero_point.cc:75:24:   required from here
/usr/include/c++/10/bits/stl_vector.h:401:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type
  401 |       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
      |                                                                  ^~~~~
```

Closes https://github.com/google/ruy/pull/278

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/ruy/pull/278 from keichi:fix-compilation-err 2e30471e9ce525f3a62337078cf2e80f17c966ff
PiperOrigin-RevId: 395965795