Only import <sys/time.h> if we are running on Linux. Otherwise it causes the following error on Windows: tensorflow/lite/experimental/ruy/time.h(19): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
PiperOrigin-RevId: 262434847